# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: NCPI-DD-on-FHIR-Implementation-Guide
canonical: https://nih-NCPI.github.io/ncpi-dd-on-fhir-ig
name: NCPI-DDonFHIR-Implementation-Guide
title: NCPI DD on FHIR Implementation Guide
description: "Example FHIR model for reprenting Data Dictionaries on FHIR for NCPI Studies."
status: draft
license: CC0-1.0
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: NCPI FHIR Working Group
  url: https://github.com/nih-NCPI
contact:
  - name: Eric Torstenson
    telecom:
      - system: email
        value: eric.s.torstenson@vumc.org
        use: work
dependencies:
  hl7.fhir.us.core: 3.1.1

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Table of Contents: toc.html
  Background:
    Authors: authors.html
    Contact: contact.html
  Artifacts: artifacts.html
  Support: 
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    Downloads: downloads.html

